#ifndef ERROR_CODES_H
#define ERROR_CODES_H

enum eErrCodes: int {
    SUCCESS,
    INIT_FAIL,
    INTERRUPT_REGISTER_FAILED,
    TRANS_TIMEOUT,
    TRANS_LOCK_FAILED,
    RESET_FAILED,
    BOUNDS_ERR,
};

#endif